---
# tasks file for roles/versioncontrol-utils

- name: system packages | install epel repo
  become: true
  yum:
    name: epel-release
    state: present

- name: system packages | basic system utils
  become: true
  yum:
    name: ['git']
    state: present
